name: bab_babbab_front
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  google_sign_in: ^6.2.2
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.5
  dropdown_button2: ^2.3.9 
  image_picker: ^0.8.7
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
      - asset: assets/fonts/Pretendard.ttf
      
  assets:
    - assets/logo/
    - assets/fonts/
    - assets/icon/